version: '2'

services:
  wordpress:
    container_name: "${project}_wordpress"
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - ../src/plugin:/var/www/html/wp-content/plugins/podlove-web-player
    environment:
      WORDPRESS_DB_PASSWORD: "${database_password}"

  mysql:
    container_name: "${project}_database"
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${database_password}"
